// ARCHIVO: src/mapConfig.js
// IMPORTACION CENTRALIZADA DE CONFIGURACION CARTOGRAFICA

import mapConfigData from './mapConfig.json';

// ESTA CONFIGURACION SE ACTIVA Y MONTA ABSOLUTAMENTE DESDE EL DOCUMENTO JSON INICIAL
export const MAP_CONFIG = mapConfigData;
